### ISSUE TITLE
Error creating botany seed

### ISSUE THREAD

**Issue by NoobCheeks101** [BobVarioa/kjsbotanypots#1]
Running ATM8 with extra mods - kubejs botany pots, botany pot ores and a few others.

I've created a kubejs file in the server_scripts section:

File Name - CruxSeeds:  
```
ServerEvents.recipes(event => {
    event.recipes.botanypots.crop(
        "mysticalagriculture:allthemodium_seeds", // seed item
        ["kubejs:farmland/insanium"], // categories that this crop can be planted on
        1000, // growthTicks
        1, // growthModifier - this can be set to 1 in most cases
        { block: "mysticalagriculture:crops" }, // display block
        [
            {
                output: "mysticalagriculture:allthemodium_essence", // item
                chance: 100, // weight of this entry compared to the others
                minRolls: 1, // the minimum times this loot will be chosen
                maxRolls: 2, // the maximum times this loot will be chosen
                // for example, when chosen this will give 1 to 2 candles
            }
        ]
    )
})

// fired everytime a crop grows
BotanyPotsEvents.onCropGrow(event => {
  	// event.random : the random object associated with the event
  	// event.crop : a crop object describing the crop grown, use ProbeJS to find the specifics 
  	// event.originalDrops : an array of items this crop drops  
  	// event.drops : a writable array that changes the drops of the crop 
    console.log([event.random, event.crop, event.originalDrops, event.drops].join(","))
})
```

When running the game the recipe is not parsed due to the following error:
`[23:28:08] [ERROR] ! server_scripts:mods/botanypots/CruxSeeds.js:2: Failed to create recipe for type 'botanypots:crop': Unable to cast 'display:com.bobvarioa.kubejsbotanypots.components.DisplayComponent@14d7703f[]' value '1000.0' to 'array'!`

I'm not quite sure what I've done wrong as there isn't much documentation that I've found and i copied/pasted the template from the wiki - modified it to suit my needs.

Here is the complete kubejs server log.
[server.log](https://github.com/BobVarioa/kjsbotanypots/files/13193728/server.log)

**SideNote:**
Also just as a side note, it would be useful to know what blocks can be used as categories - is it an oredict?

**Comment by NoobCheeks101** [comment]
Looking at the CropRecipeJS.java I see that the recipe schema takes the information in the following format:
`RecipeSchema SCHEMA = new RecipeSchema(SEED, CATEGORIES, DISPLAY, DROPS, GROWTH_TICKS, GROWTH_MODIFIER)`
```
**CORRECT FORMAT:**
- SEED
- CATEGORIES
- DISPLAY BLOCK
- DROPS
- GROWTH_TICKS
- GROWTH_MODIFIER

```
Not as the documentation on "https://wiki.latvian.dev/books/kubejs/page/kubejs-botany-pots" described:
```
**INCORRECT FORMAT**
- SEED
- CATEGORIES
- GROWTH_TICKS
- GROWTH_MODIFIER
- DISPLAY_BLOCK
- DROPS
```

Since this correction I have encountered a new error:
`[02:01:24] [WARN] Error parsing recipe botanypots:kjs_3mmgz6708nacwwpeehk22qu7g[botanypots:crop]: {"type":"botanypots:crop","seed":{"item":"mysticalagriculture:allthemodium_seeds"},"categories":["dirt"],"display":{"block":"allthemodium:allthemodium_block","properties":{}},"drops":[{"item":"minecraft:air","count":0,"nbt":"{}","output":"minecraft:air"}],"growthTicks":10,"growthModifier":1.0}: java.lang.NullPointerException: Cannot invoke "com.google.gson.JsonElement.getAsFloat()" because "json" is null`


Here is the new CruxSeeds.JS File:
```
ServerEvents.recipes(event => {
    event.recipes.botanypots.crop(
        "mysticalagriculture:allthemodium_seeds", // seed item
        ["dirt"], // categories that this crop can be planted on
        { block: "allthemodium:allthemodium_block" }, // display block
        [
            {
                output: "mysticalagriculture:allthemodium_essence", // item
                chance: 100, // weight of this entry compared to the others
                minRolls: 1, // the minimum times this loot will be chosen
                maxRolls: 2, // the maximum times this loot will be chosen
                // for example, when chosen this will give 1 to 2 candles
            }
        ],
	10, // growthTicks
        1 // growthModifier - this can be set to 1 in most cases
    )
	
	event.recipes.botanypots.soil(
        "kubejs:magical_soil", // the item that this soil is attached to
        { block: "kubejs:magical_soil" }, // display block
        ["kubejs:magical_soil"], // categories that this soil provides
        100, // growth ticks that this soil will provide, set to -1 for no modifier
        0.5 // optional, growth modifier, example: 0.5 means all crops will take half the time
    )
})

// fired everytime a crop grows
BotanyPotsEvents.onCropGrow(event => {
  	// event.random : the random object associated with the event
  	// event.crop : a crop object describing the crop grown, use ProbeJS to find the specifics 
  	// event.originalDrops : an array of items this crop drops  
  	// event.drops : a writable array that changes the drops of the crop 
    console.log([event.random, event.crop, event.originalDrops, event.drops].join(","))
})
```

Here's the complete log.
[server.log](https://github.com/BobVarioa/kjsbotanypots/files/13195385/server.log)

**Comment by BobVarioa** [comment]
Ah my fault, forgot to update the mod documentation. An updated version should be up shortly.
