### ISSUE TITLE
Can't use reference from online

### ISSUE THREAD

**Issue by zookeper** [BobVarioa/kjsbotanypots#2]
Copy and paste reference from 

https://wiki.latvian.dev/books/kubejs/page/kubejs-botany-pots

Into a modded world forge 47.2.16, mc 1.20.1 

I'm trying to use GeOre mod for Ars nouveau to create hopper alternative to resource generation with kubejs

Throws kubejs error about writing array

**Comment by BobVarioa** [comment]
Fixed this issue, see documentation for more info or look at #1
